["~/.tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["~/.fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["~/.local/share/oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["~/.local/share/zsh-custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["~/.local/share/zsh-custom/plugins/zsh-eza"]
    type = "archive"
    url = "https://github.com/z-shell/zsh-eza/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["~/.local/share/zsh-custom/plugins/artisan"]
    type = "archive"
    url = "https://github.com/jessarcher/zsh-artisan/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["~/.local/share/zsh-custom/plugins/zsh-bat"]
    type = "archive"
    url = "https://github.com/fdellwing/zsh-bat/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["~/.local/share/zsh-custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
["~/.local/share/zsh-custom/plugins/fast-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
