format = """
[](#b4befe)\
$os\
$username\
$hostname\
[](bg:#A6E3A1 fg:#b4befe)\
$sudo\
[](bg:#89B4FA fg:#A6E3A1)\
$directory\
[](bg:#f5e0dc fg:#89B4FA)\
$git_branch\
$git_status\
[](bg:#94E2D5 fg:#f5e0dc)\
$nodejs\
$rust\
$python\
$php\
$character\
"""
# Disable the blank line at the start of the prompt
# add_newline = false

[character]
success_symbol = "[](fg:#94E2D5 bg:#74C7EC)[ ](fg:#74C7EC)"
error_symbol = "[](fg:#94E2D5 bg:#f38ba8)[ ](fg:#f38ba8)"
vimcmd_symbol = "[](fg:#94E2D5 bg:#a6adc8)[ ](fg:#a6adc8)"

[username]
show_always = false
style_user = "fg:#45475a bg:#b4befe"
style_root = "fg:#45475a bg:#b4befe"
format = '[ $user]($style)'
disabled = false

[hostname]
ssh_only = true
format = '[@](fg:#45475a bg:#b4befe)[$hostname](fg:#45475a bg:#b4befe)'

[os]
style = "fg:#45475a bg:#b4befe"
disabled = false # Disabled by default

[sudo]
style = "bg:#A6E3A1 fg:#45475a"
format = "[ 󱎛]($style)"
disabled = false

[shell]
disabled = false
style = "bg:#A6E3A1 fg:#45475a"
format = "[$indicator]($style)"
fish_indicator = " f"
bash_indicator = " b"
zsh_indicator = " z"

[directory]
style = "bg:#89B4FA fg:#45475a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[os.symbols]
Arch = "󰣇 "
Debian = " "
Fedora = " "
Linux = " "
Mint = "󰣭 "
NixOS = "󱄅 "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Ubuntu = " "
Unknown = " "

[git_branch]
symbol = ""
style = "bg:#f5e0dc fg:#45475A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f5e0dc fg:#45475A"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:#94E2D5 fg:#45475A"
format = '[ $symbol ($version) ]($style)'
version_format = "${raw}"

[rust]
symbol = ""
style = "bg:#94E2D5 fg:#45475A"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#94E2D5 fg:#45475A"
format = '[ ${symbol}($virtualenv $version) ]($style)'
version_format = "${raw}"

[php]
symbol = "󰌟 "
style = "bg:#94E2D5 fg:#45475A"
format = '[$symbol$version ]($style)'
version_format = "${raw}"
