format = """
$os\
$line_break\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$line_break\
$character"""

right_format = """
$status\
$commnad_duration\
$sudo"""

[directory]
style = "bold cyan"
truncation_length = 4
truncate_to_repo = false
truncation_symbol = '…/'

[username]
style_user = 'yellow'
style_root = 'black bold'
format = '[$user]($style)@'
disabled = false
show_always = false

[hostname]
ssh_only = true
format = '(bold blue)[$hostname](green) '
disabled = false

[line_break]
disabled = true

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[os]
disabled = false
style = "bold blue"

[os.symbols]
Arch = "󰣇 "
Debian = " "
Fedora = " "
Linux = " "
Mint = "󰣭 "
NixOS = "󱄅 "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Ubuntu = " "
Unknown = " "

[status]
disabled = false

[sudo]
format='[$symbol]($style)'
disabled = false
symbol = " "
style = "bright-cyan"

[php]
format = '[$symbol$version]($style)'
symbol = '󰌟 '
version_format = '${patch}'

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
